image: gcc

before_script:
  - apt update && apt -y install make cmake

build:
  stage: build
  script:
    - cmake . -DBUILD_TESTS=ON
    - make
  artifacts:
    paths:
      - ./bin/markus-test

test:
  stage: test
  script:
    - ./bin/markus-test