image: gcc

build:
  stage: build
  script:
    - apt update && apt -y install ninja-build cmake
    - cmake . -G Ninja
    - ninja
  artifacts:
    paths:
      - ./bin/markus-test
      - ./bin/markus-dump

test:
  stage: test
  script:
    - ./bin/markus-test
    - apt-get update -qy
    - apt-get install -y python-dev
    - python suite/test.py